### ISSUE TITLE
希望可以加入去掉边框的选项

### ISSUE THREAD

**Issue by CL-Jeremy** [issue9/identicon#6]
感谢作者制作了这个方便的库，在本地也可以比较简单地模仿 WP identicon（通过修改最终的绘制函数）。

目前在尝试为一个开源项目定制一个修改版，直接制作成接近 Gravatar 的风格（即 WP 风格）但尽量使图案“破碎”一些，以免造成[不当的联想](https://codeberg.org/Codeberg/avatars/issues/1)（是的，这个动机非常可笑，而且有佛教徒抗议这种捆绑行为）并为此添加和删除了一些块。目前的代码在[这里](https://piramisancchi.live-on.net:9175/gitea/identicon)（我自己的私有库，还没有提交给上游审核）。

现在的问题是，由于有的块之间需要无缝连接，需要去掉块周围的边框，但在现有的框架上并不容易实现。现在的方案非常牵强，不知能否抽点时间协助一下呢，非常感谢！

**Comment by caixw** [comment]
不是很理解你的意思，如果你说的是原来定义的那几种方块是一个多边形，现在因为你要做得“破碎”的需求，变成了多个多边形，无法生成旋转一定角度之后的图案。我的建议是把原来的九宫格改成 25 格的，然后每个小方块的图案依然采用单个多边形。

**Comment by CL-Jeremy** [comment]
不是的，我现在使用的是 16 宫格，每个块中确实有数量不等的多边形（原来也有部分块是这样的）。

如果查看我代码中上一个 commit，那时候已经在设计上实现我的要求了，理论上也可以直接使用，但我个人希望的是，polygon.go 中的判定函数在判定时包括一像素的边框，这样在绘制的时候是顶格的，而不会是现在这样，每次绘制会在周围留下一像素的空隙。

**Comment by caixw** [comment]
https://github.com/issue9/identicon/blob/ded8200f47e57dd83b10b6ff1eab65353e88e72b/polygon.go#L55

改成 `>= 0` 应该会有所改善。
还有就是将坐标值类型从 `float64` 改成 `int`，不存在小数换算的差值也会好很多。

**Comment by CL-Jeremy** [comment]
> 改成 `>= 0` 应该会有所改善。

我确实是这样改的
https://piramisancchi.live-on.net:9175/gitea/identicon/commit/a8ea9ddea9c6fc25082bb19177d59d32312d0d35

> 还有就是将坐标值类型从 `float64` 改成 `int`，不存在小数换算的差值也会好很多。

有道理，我目前确实只需要用到宽度的 1/8，确实比三等分对小数依赖较少
